### ISSUE TITLE
no-sound-null-safety

### ISSUE THREAD

**Issue by mugri-ndeh** [ndemeyvan/pay_unit_sdk#1]
I get build error no-sound-null safety when i try to install my app

**Comment by mugri-ndeh** [comment]
Ok so i can now run it with from terminal with flutter run --no-sound-null-safety

**Comment by ndemeyvan** [comment]
hello and thank you for writing to me. a package that depends on other
packages that are not null safety cannot be null safety ...
But  bypassing this problem is very simple, when installing the package
follow the steps  and  add @dart = {dart version} to the main.dart or to
the class where payUnit should be implemented
Please use the most recent new versions of the payUnit package

Le mer. 18 août 2021 à 13:37, mugri-ndeh ***@***.***> a
écrit :

**Comment by mugri-ndeh** [comment]
Thanks for the response.
I've managed to run the app but I've not been able to initiate any
transaction. Even when I put the phone number I get a success notification
when nothing happens
I'm having trouble understanding a few fields on the button.
The notifyurl, transactionCallBackUrl, isTerminalPayment and hasConnection

**Comment by ndemeyvan** [comment]
Let have a Google meet Tomorrow and show me . I'am going toi send you a
link later .

Le mer. 18 août 2021 à 18:01, mugri-ndeh ***@***.***> a
écrit :

> Thanks for the response.
> I've managed to run the app but I've not been able to initiate any
> transaction. Even when I put the phone number I get a success notification
> when nothing happens
> I'm having trouble understanding a few fields on the button.
> The notifyurl, transactionCallBackUrl, isTerminalPayment and hasConnection
>

**Comment by mugri-ndeh** [comment]
Ok thank you I'm waiting

**Comment by mugri-ndeh** [comment]
Hello greetings
Reminder about our meeting
You haven't sent me the Google meet link yet

**Comment by ndemeyvan** [comment]
Hi, I'm really sorry, I was too busy yesterday and completely forgot. Once
again I'm sorry, I'll send you a meet during the day.

Le jeu. 19 août 2021, à 21 h 55, mugri-ndeh ***@***.***> a
écrit :

> Hello greetings
> Reminder about our meeting
> You haven't sent me the Google meet link yet
>

**Comment by mugri-ndeh** [comment]
Alright cool. I prefer we have the meeting in the evening if that's ok with
you

**Comment by ndemeyvan** [comment]
ndemeyvan@gmail.com that's my email .
I am available until 6pm for this meeting, please send me an email, with the link meet at the time you have chosen I will do my best to be there

**Comment by mugri-ndeh** [comment]
Payunit
Friday, Aug 20  •  19:00 – 20:00
Google Meet joining info
Video call link: https://meet.google.com/iak-owbx-cdx
If u are not free at this time. We can do it tomorrow

**Comment by ndemeyvan** [comment]
no . I am available until 6pm for this meeting . please write me on my email .

**Comment by baimamboukar** [comment]
Faced same problem.... Why not migrating the whole package to null-safety ?

**Comment by ndemeyvan** [comment]
a package which depends on other packages which are not null-safety cannot
be null safety .
I advise you to follow exactly the procedure which is given in the example
of the package on pub.deI advise you to follow exactly the procedure which
is given in the example of the package on pub.dev , In case of error please
share your logs with us.

Pay attention to ***@***.***=2.9 Follow exactly what is done in the doc

**Comment by ndemeyvan** [comment]
hope you found a solution to your problem

Le dim. 5 sept. 2021 à 17:54, mugri-ndeh ***@***.***> a
écrit :

**Comment by mugri-ndeh** [comment]
Yes thank you
